controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

blog_index:
  path: /{_locale}/blog
  controller: App\Controller\Front\Resources\BlogController::index
  requirements:
    _locale: fr|en


blog_article_show:
  path: /{_locale}/blog/{slug}
  controller: App\Controller\Front\Resources\BlogController::show
  requirements:
    _locale: fr|en    
